/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package axc.g1l3.servidor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Ignacio
 */
public class Ventana extends javax.swing.JFrame
{

    /**
     * Creates new form Ventana
     */
    public Ventana(int clientes, int grupos, int iteraciones) throws FileNotFoundException
    {
        initComponents();
        if(clientes%grupos==0)
            TextMaximo.setText(String.valueOf(clientes/grupos));
        else
            TextMaximo.setText(String.valueOf((clientes/grupos)+1));
        TextClientes.setText("0");
        TextSalas.setText(String.valueOf(grupos));
        this.setVisible(true);
        servidor=new Servidor(clientes,grupos,iteraciones,this);    //Creación del objeto
    }

    public void SetClientes(int clientes)
    {
        TextClientes.setText(String.valueOf(clientes));
    }
    
    public void SetSalas(int salas)
    {
        TextSalas.setText(String.valueOf(salas));
    }
    
    public void SetIteraciones(int i)
    {
        TextIteracion.setText(String.valueOf(i));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        BotonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextMaximo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextClientes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextSalas = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        BotonInicio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TextIteracion = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Info = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalir.setText("Desconectar");
        BotonSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, 40));

        jLabel1.setText("Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 40));

        jLabel2.setText("Salas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 40));

        TextMaximo.setColumns(20);
        TextMaximo.setRows(1);
        jScrollPane1.setViewportView(TextMaximo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, 30));

        TextClientes.setColumns(20);
        TextClientes.setRows(1);
        TextClientes.setEnabled(false);
        jScrollPane2.setViewportView(TextClientes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, 30));

        jLabel3.setText("Máximo Clientes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 30));

        TextSalas.setColumns(20);
        TextSalas.setRows(1);
        jScrollPane3.setViewportView(TextSalas);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 30));

        jLabel4.setText("por sala");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        BotonInicio.setText("Iniciar Prueba");
        BotonInicio.setEnabled(false);
        BotonInicio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BotonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, 40));

        jLabel5.setText("Iteración");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        TextIteracion.setText("0");
        getContentPane().add(TextIteracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, 30));

        Info.setEditable(false);
        Info.setColumns(20);
        Info.setRows(1000);
        jScrollPane4.setViewportView(Info);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 370, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotonSalirActionPerformed
    {//GEN-HEADEREND:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotonInicioActionPerformed
    {//GEN-HEADEREND:event_BotonInicioActionPerformed
        servidor.LanzarPrueba();
        BotonInicio.setEnabled(false);
    }//GEN-LAST:event_BotonInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                try {
                    new Ventana(clientes,grupos,iteraciones).setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTextArea Info;
    private javax.swing.JTextArea TextClientes;
    private javax.swing.JTextField TextIteracion;
    private javax.swing.JTextArea TextMaximo;
    private javax.swing.JTextArea TextSalas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
static int clientes;
Servidor servidor;
static int grupos;
static int iteraciones;

    void Lanzar()
    {
        BotonInicio.setEnabled(true);
    }

    void print(String linea)
    {
        Info.setText(Info.getText()+linea);
    }
}
